// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_EMUS.Data;

#nullable disable

namespace Proyecto_EMUS.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240703072230_ModificationClinicalHistoryNote")]
    partial class ModificationClinicalHistoryNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_EMUS.Models.ClinicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicalHistories");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.ClinicalHistoryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalHistoryId");

                    b.ToTable("ClinicalHistoryNotes");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Conditions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Doctor", b =>
                {
                    b.Property<int>("GMCNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GMCNumber"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GMCNumber");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.DoctorSpecialty", b =>
                {
                    b.Property<int>("GMCNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdSpecialty")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("GMCNumber", "IdSpecialty");

                    b.HasIndex("IdSpecialty");

                    b.ToTable("DoctorSpecialty");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.LaboratoryExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LaboratoryExams");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendingDoctor")
                        .HasColumnType("int");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DayOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastAttendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AttendingDoctor");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientCondition", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdCondition")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("IdPatient", "IdCondition");

                    b.HasIndex("IdCondition");

                    b.ToTable("PatientConditions");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientLaboratoryExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLaboratoryExam")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdLaboratoryExam");

                    b.HasIndex("IdPatient");

                    b.ToTable("PatientLaboratoryExam");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientMedication", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdMedication")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("IdPatient", "IdMedication");

                    b.HasIndex("IdMedication");

                    b.ToTable("PatientMedication");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientTreatment", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTreatment")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("IdPatient", "IdTreatment");

                    b.HasIndex("IdTreatment");

                    b.ToTable("PatientTreatment");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatment");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.ClinicalHistory", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.ClinicalHistoryNote", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.ClinicalHistory", "ClinicalHistory")
                        .WithMany("ClinicalHistoryNotes")
                        .HasForeignKey("ClinicalHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalHistory");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.DoctorSpecialty", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("GMCNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EMUS.Models.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("IdSpecialty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Patient", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("AttendingDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientCondition", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Conditions", "Conditions")
                        .WithMany()
                        .HasForeignKey("IdCondition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EMUS.Models.Patient", "Patient")
                        .WithMany("PatientConditions")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conditions");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientLaboratoryExam", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.LaboratoryExam", "LaboratoryExam")
                        .WithMany()
                        .HasForeignKey("IdLaboratoryExam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EMUS.Models.Patient", "Patient")
                        .WithMany("PatientLaboratoryExams")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaboratoryExam");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientMedication", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("IdMedication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EMUS.Models.Patient", "Patient")
                        .WithMany("PatientMedication")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.PatientTreatment", b =>
                {
                    b.HasOne("Proyecto_EMUS.Models.Patient", "Patient")
                        .WithMany("PatientTreatments")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_EMUS.Models.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("IdTreatment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.ClinicalHistory", b =>
                {
                    b.Navigation("ClinicalHistoryNotes");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Doctor", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("Proyecto_EMUS.Models.Patient", b =>
                {
                    b.Navigation("PatientConditions");

                    b.Navigation("PatientLaboratoryExams");

                    b.Navigation("PatientMedication");

                    b.Navigation("PatientTreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
